[project]
name = "backend-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "cloudinary>=1.44.2",
    "fastapi[standard]>=0.136.0",
    "greenlet>=3.4.0",
    "itsdangerous>=2.2.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.26",
    "sqladmin>=0.25.0",
    "sqlalchemy-utils>=0.42.1",
    "sqlmodel>=0.0.38",
    "uvicorn>=0.45.0",
]
