"""Initial migration and update blog tags to JSON array

Revision ID: e29778430e92
Revises: 
Create Date: 2026-05-01 00:16:45.883742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29778430e92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'tags',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using="'[]'::json")
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('blog', 'tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
