import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { site } from '../data/site';
import { Github, Linkedin, Instagram, Mail } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
const socials = { GitHub: Github, LinkedIn: Linkedin, Instagram: Instagram };
export default function Footer() {
    const navigate = useNavigate();
    const gotoContact = () => { navigate('/#contact'); setTimeout(() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }), 50); };
    return (_jsxs("footer", { className: "mt-16 border-t border-border", children: [_jsxs("div", { className: "mx-auto max-w-6xl px-4 py-8 flex flex-col md:flex-row items-center justify-between gap-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("img", { src: "/favicon.svg", alt: "Brand", className: "h-7 w-7" }), _jsx("span", { className: "font-semibold", children: site.NAME })] }), _jsxs("nav", { className: "flex flex-wrap justify-center gap-4 text-sm text-[#FFFFFF] opacity-80", children: [_jsx(Link, { to: "/#skills", className: "hover:opacity-100 hover:text-[#FF6B35]", children: "Skills" }), _jsx(Link, { to: "/#projects", className: "hover:opacity-100 hover:text-[#FF6B35]", children: "Projects" }), _jsx(Link, { to: "/certifications", className: "hover:opacity-100 hover:text-[#FF6B35]", children: "Certifications" }), _jsx(Link, { to: "/about", className: "hover:opacity-100 hover:text-[#FF6B35]", children: "About" }), _jsx(Link, { to: "/resume", className: "hover:opacity-100 hover:text-[#FF6B35]", children: "Resume" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [site.SOCIAL.map((s) => { const Icon = socials[s.label]; return (_jsx("a", { href: s.url, target: "_blank", rel: "noreferrer", "aria-label": s.label, className: "p-2 rounded-lg hover:bg-[#222]", children: Icon ? _jsx(Icon, { className: "h-5 w-5" }) : _jsx("span", { className: 'text-sm', children: s.label }) }, s.label)); }), _jsxs("button", { onClick: gotoContact, className: "inline-flex items-center gap-2 bg-gradient-brand text-[#1A1A1A] font-medium px-4 py-2 rounded-lg shadow-glow", children: [_jsx(Mail, { className: "h-4 w-4" }), " Contact"] })] })] }), _jsxs("div", { className: "text-center text-xs text-[#FFFFFF] opacity-60 py-4", children: ["\u00A9 ", new Date().getFullYear(), " ", site.NAME, ". All rights reserved."] })] }));
}
